title: Cameron Ibrahim
author: Cameron Ibrahim
logo: /assets/img/cat.jpg
description: Personal Website & Blog
show_downloads: false
theme: jekyll-theme-minimal

email: contact@cameronibrahim.com
twitter: cam_a_ibrahim
github: cameton
